// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vfacjktkzackwthtxfgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmYWNqa3RremFja3d0aHR4Zmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MTQxMzksImV4cCI6MjA3OTM5MDEzOX0.QX_qz6Kll0YDArVam72WwVp5RNOs9k1WwJSDJmHQ3R4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
